In [2]:
import tensorflow as tf
import numpy as np

x_input_pc = tf.placeholder(tf.float32, shape=(4,2), name="x-input")
y_target_pc = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

# layers: 2 inputs -2-> fc -2-> fc -1-> 1 oputput
# weights of fully connected layers
(1)    # 2 inputs 2 outputs
(2)    # 2 inputs 1 output

# biases of fully connected layers
(3)    # 2 biases for 2 output
(4)    # 2 biases for 1 output

    
    
(5)    # input -> hidden graph
(6)    # hidden -> output graph

error = (y_target_pc - y_output)

cost = tf.reduce_mean(tf.multiply(error, error), name="cost")

# node of tensorflow
train_step = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

# XOR training data
# shape of data should match shape of placeholders
x_train = [[0,0],[0,1],[1,0],[1,1]] #shape=[4, 2]
y_test = [[0],[1],[1],[0]] #shape=[4, 1]

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

tf.train.write_graph(sess.graph_def, 'xor_models/', 'xor_graph.pb', as_text=True)
np.set_printoptions(precision=1)
for i in range(100000):
    sess.run(train_step, feed_dict={x_input_pc: x_train, y_target_pc: y_test})
    # print some results
    if ( i % 10000 == 0):
        print('y_output \n', sess.run(y_output, feed_dict={x_input_pc: x_train, y_target_pc: y_test}))
        error_result = sess.run(error, feed_dict={x_input_pc: x_train, y_target_pc: y_test})
        #print(type(error_result))
        print('error ', error_result.flatten().dot(error_result.flatten()))

y_output 
 [[0.]
 [0.]
 [0.]
 [0.]]
error  1.9004579
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.95612836
y_output 
 [[0.2]
 [0.5]
 [0.7]
 [0.5]]
error  0.6268535
y_output 
 [[0. ]
 [0.6]
 [0.9]
 [0.4]]
error  0.34005412
y_output 
 [[0. ]
 [0.9]
 [1. ]
 [0.1]]
error  0.011284942
y_output 
 [[0.]
 [1.]
 [1.]
 [0.]]
error  5.8302812e-05
y_output 
 [[1.3e-04]
 [1.0e+00]
 [1.0e+00]
 [3.6e-04]]
error  2.567006e-07
y_output 
 [[3.8e-05]
 [1.0e+00]
 [1.0e+00]
 [9.7e-05]]
error  1.833719e-08
y_output 
 [[9.7e-06]
 [1.0e+00]
 [1.0e+00]
 [6.0e-05]]
error  5.6806346e-09
y_output 
 [[1.2e-05]
 [1.0e+00]
 [1.0e+00]
 [5.8e-05]]
error  5.5932263e-09
