In [7]:
import tensorflow as tf
import numpy as np

x_input_pc = tf.placeholder(tf.float32, shape=(4,2), name="x-input")
y_target_pc = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

# layers: 2 inputs -2-> fc -2-> fc -1-> 1 oputput
# weights of fully connected layers
w1=tf.Variable(tf.random_uniform([2,2],-1.,1.))    # 2 inputs 2 outputs
w2=tf.Variable(tf.random_uniform([2,1],-1.,1.))    # 2 inputs 1 output

# biases of fully connected layers
bias1 = tf.Variable(tf.zeros([2]))    # 2 biases for 2 output
bias2 = tf.Variable(tf.zeros([1]))    # 2 biases for 1 output

h1_output=tf.add(tf.matmul(x_input_pc,w1),bias1)
h1_sigmoid=tf.nn.sigmoid(h1_output)#input -> hidden graph
output=tf.add(tf.matmul(h1_sigmoid,w2),bias2) 
y_output=tf.nn.sigmoid(output)
# hidden -> output graph

error = (y_target_pc - y_output)

cost = tf.reduce_mean(tf.multiply(error, error), name="cost")

# node of tensorflow
train_step = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# XOR training data
# shape of data should match shape of placeholders
x_train = [[0,0],[0,1],[1,0],[1,1]] #shape=[4, 2]
y_test = [[0],[1],[1],[0]] #shape=[4, 1]

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

tf.train.write_graph(sess.graph_def, 'xor_models/', 'xor_graph.pb', as_text=True)
np.set_printoptions(precision=1)
for i in range(200000):
    sess.run(train_step, feed_dict={x_input_pc: x_train, y_target_pc: y_test})
    # print some results
    if ( i % 10000 == 0):
        print('y_output \n', sess.run(y_output, feed_dict={x_input_pc: x_train, y_target_pc: y_test}))
        error_result = sess.run(error, feed_dict={x_input_pc: x_train, y_target_pc: y_test})
        #print(type(error_result))
        print('error ', error_result.flatten().dot(error_result.flatten()))

y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  1.0018569
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.9998451
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.99970555
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.9994439
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.99893993
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.99790424
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.9954814
y_output 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error  0.9886092
y_output 
 [[0.5]
 [0.4]
 [0.6]
 [0.5]]
error  0.96567583
y_output 
 [[0.5]
 [0.4]
 [0.6]
 [0.4]]
error  0.8988781
y_output 
 [[0.4]
 [0.4]
 [0.7]
 [0.4]]
error  0.7864161
y_output 
 [[0.4]
 [0.5]
 [0.8]
 [0.3]]
error  0.5980635
y_output 
 [[0.3]
 [0.6]
 [0.8]
 [0.2]]
error  0.28559124
y_output 
 [[0.2]
 [0.8]
 [0.9]
 [0.2]]
error  0.12873597
y_output 
 [[0.1]
 [0.8]
 [0.9]
 [0.1]]
error  0.073582806
y_output 
 [[0.1]
 [0.9]
 [0.9]
 [0.1]]
error  0.049337495
y_output 
 [[0.1]
 [0.9]
 [0.9]
 [0.1]]
error  0.036388278
y_output 
 [[0.1]
 