# Exercise 1. Using Custom Dataset

#### Sample Data
![Sample](./sample_data.jpg)

In [1]:
import numpy as np

# sex, age, income
X_train = np.array(([1.0, 0.7, 0.17], #1
                    [-1.0, -1, -0.6], #2
                    [-1.0, 0.25, 0.4], #3
                    [1.0, -0.1, 0.6], #4
                    [-1.0, -0.75, -1], #5
                    [1.0, -0.5, 0.27], #6
                    [1.0, 0.4, -0.27], #7
                    [-1.0, -0.4, -0.33], #8
                   ), dtype=float)

# vote(+), vote(-)
y_train = np.array(([1, 0], #1
                    [0, 1], #2
                    [1, 0], #3
                    [0, 1], #4
                    [1, 0], #5
                    [0, 1], #6
                    [1, 0], #7
                    [1, 0], #8
                   ), dtype=float)

X_test = np.array(([1.0, -0.55, -0.23]), dtype=float)
y_test = np.array(([0, 1]), dtype=float)


class Neural_Network(object):
    def __init__(self):
        # fill the folkowing (1), (2), (3)
        #parameters
        self.inputSize=3
        self.hiddenSize=5
        self.outputSize=2

        #weights
        self.w1 = np.random.randn(self.inputSize, self.hiddenSize) # (inputSize x hiddenSize) weight matrix from input to hidden layer
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize) # (hiddenSize x outputSize) weight matrix from hidden to output layer
    
    def forward(self, X):
        #implementation forward function
        self.h1_weighted_sum = np.dot(X, self.w1) # dot product of X (input) and first set of (inputSize x hiddenSize) weights
        self.h1_output = self.sigmoid(self.h1_weighted_sum) # activation function
        
        #fill the following (1), (2)
        self.out_weighted_sum=np.dot(self.h1_output,self.w2)# dot product of hidden layer (h1_output) and second set of (hiddenSize x outputSize) weights
        output=self.sigmoid(self.out_weighted_sum)
        
        return output

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o, alpha):
        #implementation backward function
        self.o_error = (y - o) # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # applying derivative of sigmoid to error

        #fill the following (3), (4), (5), (6)
        self.h1_error =np.dot(self.o_delta,self.w2.T) # h1 error: how much our hidden layer weights contributed to output error
        self.h1_delta = self.h1_error*self.sigmoidPrime(self.h1_output) # applying derivative of sigmoid to h1_output error

        self.w1 += 0.1*np.dot(X.T,self.h1_delta)# adjusting first set (input --> hidden) weights
        self.w2 += 0.1*np.dot(self.h1_output.T,self.o_delta)


    def train(self, X, y, alpha):
        o = self.forward(X)
        self.backward(X, y, o, alpha)

    def saveWeights(self):
        np.savetxt("custom_w1.txt", self.w1, fmt="%s")
        np.savetxt("custom_w2.txt", self.w2, fmt="%s")

    def predict(self):
        print("\n\n####################")
        print("Final Results...")
        print("####################\n")
        print("Predicted data based on trained weights: ")
        print("\n<Train data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_train)))
        print("\n<Test data>")
        print("Input: \n" + str(X_test))
        print("Actual Output: \n" + str(y_test))
        print("Predicted Output: \n" + str(self.forward(X_test)))
        

# set a parameter
epoch = int(2e6)
display_step = int(1e5)
alpha = 0.0001
        
NN = Neural_Network()

for i in range(epoch): # trains the NN 1,000 times
    if i % display_step == 0:
        print("\n# " + str(i) + "\n")
        print("Input: \n" + str(X_test))
        print("Actual Output: \n" + str(y_test))
        print("Predicted Output: \n" + str(NN.forward(X_test)))
        print("Loss: \n" + str(np.mean(np.square(y_test - NN.forward(X_test)))))# mean sum squared loss
        print()
    NN.train(X_train, y_train, alpha)

print("\n\n####################")
print("Train is Done...")
print("####################\n")

print("\n# " + str(i) + "\n")
print("Input: \n" + str(X_train))
print("Actual Output: \n" + str(y_train))
print("Predicted Output: \n" + str(NN.forward(X_train)))
print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
print()

NN.saveWeights()
NN.predict()


# 0

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.28981283 0.44371909]
Loss: 
0.1967199621115716


# 100000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[8.50333655e-04 9.99092301e-01]
Loss: 
7.734926274680982e-07


# 200000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[5.64394725e-04 9.99395309e-01]
Loss: 
3.4209646865926964e-07


# 300000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[4.45824379e-04 9.99521694e-01]
Loss: 
2.1376791418611044e-07


# 400000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[3.77694468e-04 9.99594495e-01]
Loss: 
1.5354386766224613e-07


# 500000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[3.32360760e-04 9.99643005e-01]
Loss: 
1.189546468342484e-07


# 600000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[2.99530456e-04 9.99678168e-01]
Loss: 
9.664712396507964e-08


# 70