# Exercise 1. Using Custom Dataset

#### Sample Data
![Sample](./sample_data.jpg)

In [1]:
import numpy as np

# sex, age, income
X_train = np.array(([1.0, 0.7, 0.17], #1
                    [-1.0, -1, -0.6], #2
                    [-1.0, 0.25, 0.4], #3
                    [1.0, -0.1, 0.6], #4
                    [-1.0, -0.75, -1], #5
                    [1.0, -0.5, 0.27], #6
                    [1.0, 0.4, -0.27], #7
                    [-1.0, -0.4, -0.33], #8
                   ), dtype=float)

# vote(+), vote(-)
y_train = np.array(([1, 0], #1
                    [0, 1], #2
                    [1, 0], #3
                    [0, 1], #4
                    [1, 0], #5
                    [0, 1], #6
                    [1, 0], #7
                    [1, 0], #8
                   ), dtype=float)

X_test = np.array(([1.0, -0.55, -0.23]), dtype=float)
y_test = np.array(([0, 1]), dtype=float)


class Neural_Network(object):
    def __init__(self):
        # fill the folkowing (1), (2), (3)
        #parameters
        (1)
        (2)
        (3)

        #weights
        self.w1 = np.random.randn(self.inputSize, self.hiddenSize) # (inputSize x hiddenSize) weight matrix from input to hidden layer
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize) # (hiddenSize x outputSize) weight matrix from hidden to output layer
    
    def forward(self, X):
        #implementation forward function
        (4)

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o, alpha):
        #implementation backward function
        (5)


    def train(self, X, y, alpha):
        o = self.forward(X)
        self.backward(X, y, o, alpha)

    def saveWeights(self):
        np.savetxt("custom_w1.txt", self.w1, fmt="%s")
        np.savetxt("custom_w2.txt", self.w2, fmt="%s")

    def predict(self):
        print("\n\n####################")
        print("Final Results...")
        print("####################\n")
        print("Predicted data based on trained weights: ")
        print("\n<Train data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_train)))
        print("\n<Test data>")
        print("Input: \n" + str(X_test))
        print("Actual Output: \n" + str(y_test))
        print("Predicted Output: \n" + str(self.forward(X_test)))
        

# set a parameter
epoch = int(2e6)
display_step = int(1e5)
alpha = 0.0001
        
NN = Neural_Network()

for i in range(epoch): # trains the NN 1,000 times
    if i % display_step == 0:
        print("\n# " + str(i) + "\n")
        print("Input: \n" + str(X_test))
        print("Actual Output: \n" + str(y_test))
        print("Predicted Output: \n" + str(NN.forward(X_test)))
        print("Loss: \n" + str(np.mean(np.square(y_test - NN.forward(X_test)))))# mean sum squared loss
        print()
    NN.train(X_train, y_train, alpha)

print("\n\n####################")
print("Train is Done...")
print("####################\n")

print("\n# " + str(i) + "\n")
print("Input: \n" + str(X_train))
print("Actual Output: \n" + str(y_train))
print("Predicted Output: \n" + str(NN.forward(X_train)))
print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
print()

NN.saveWeights()
NN.predict()


# 0

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.83122129 0.53201343]
Loss: 
0.4549701288760981


# 100000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.48155505 0.57169596]
Loss: 
0.20766980787460337


# 200000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.27841656 0.78569513]
Loss: 
0.061721178023549664


# 300000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.16729403 0.8737717 ]
Loss: 
0.021960437646631185


# 400000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.11324481 0.91529524]
Loss: 
0.009999641680960583


# 500000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.08354209 0.93765365]
Loss: 
0.005433174193936865


# 600000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
Predicted Output: 
[0.06537662 0.95108722]
Loss: 
0.003333281307513083


# 700000

Input: 
[ 1.   -0.55 -0.23]
Actual Output: 
[0. 1.]
