## Exercise 1. SOLVIGN A XOR PROBLEM

#### XOR PROBLEM
![XOR](./XOR_problem.jpg)

#### NN example for XOR Problem
![NN_Example](./NN_example.jpg)

In [3]:
import numpy as np

X_train = np.array(([0, 0], [0, 1], [1, 0], [1, 1]), dtype=float)
y_train = np.array(([0], [1], [1], [0]), dtype=float)

X_test = np.array(([0, 0], [0, 1], [1, 0], [1, 1]), dtype=float)
y_test = np.array(([0], [1], [1], [0]), dtype=float)

# scale units
#X_train = X_train / np.amax(X_train, axis=0) # maximum of X array
#X_test = X_test / np.amax(X_test, axis=0) # maximum of X_test (our input data for the prediction)

class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 10

        #weights
        self.w1 = np.random.randn(self.inputSize, self.hiddenSize) # (inputSize x hiddenSize) weight matrix from input to hidden layer
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize) # (hiddenSize x outputSize) weight matrix from hidden to output layer
    
    def forward(self, X):
        #forward propagation through our network
        self.h1_weighted_sum = np.dot(X, self.w1) # dot product of X (input) and first set of (inputSize x hiddenSize) weights
        self.h1_output = self.sigmoid(self.h1_weighted_sum) # activation function
        
        #fill the following (1), (2)
        self.out_weighted_sum=np.dot(self.h1_output,self.w2)# dot product of hidden layer (h1_output) and second set of (hiddenSize x outputSize) weights
        output=self.sigmoid(self.out_weighted_sum)# final activation function

        return output

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o, alpha):
        # backward propagate through the network
        self.o_error = (y - o) # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # applying derivative of sigmoid to error

        #fill the following (3), (4), (5), (6)
        self.h1_error =np.dot(self.o_delta,self.w2.T) # h1 error: how much our hidden layer weights contributed to output error
        self.h1_delta = self.h1_error*self.sigmoidPrime(self.h1_output) # applying derivative of sigmoid to h1_output error

        self.w1 += np.dot(X.T,self.h1_delta)# adjusting first set (input --> hidden) weights
        self.w2 += np.dot(self.h1_output.T,self.o_delta)# adjusting second set (hidden --> output) weights

    def train(self, X, y, alpha):
        o = self.forward(X)
        self.backward(X, y, o, alpha)

    def saveWeights(self):
        np.savetxt("w1.txt", self.w1, fmt="%s")
        np.savetxt("w2.txt", self.w2, fmt="%s")

    def predict(self):
        print("\n\n####################")
        print("Final Results...")
        print("####################\n")
        print("Predicted data based on trained weights: ")
        print("\n<Train data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_train)))
        print("\n<Test data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_test)))

# set a parameter
epoch = int(1e7)
display_step = int(1e6)
alpha = 0.0001        
        
NN = Neural_Network()

for i in range(epoch): # trains the NN 1,000 times
    if i % display_step == 0:
        print("\n# " + str(i) + "\n")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(NN.forward(X_train)))
        print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
        print()
    NN.train(X_train, y_train, alpha)

print("\n\n####################")
print("Train is Done...")
print("####################\n")

print("\n# " + str(i) + "\n")
print("Input: \n" + str(X_train))
print("Actual Output: \n" + str(y_train))
print("Predicted Output: \n" + str(NN.forward(X_train)))
print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
print()

NN.saveWeights()
NN.predict()


# 0

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.03129391]
 [0.0266546 ]
 [0.02415052]
 [0.01920663]]
Loss: 
0.4752579190156717


# 1000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.00102879]
 [0.99890895]
 [0.9989661 ]
 [0.00112499]]
Loss: 
1.1458387667774322e-06


# 2000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[7.19863579e-04]
 [9.99239519e-01]
 [9.99273817e-01]
 [7.83964545e-04]]
Loss: 
5.596194638218385e-07


# 3000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[5.84182003e-04]
 [9.99384003e-01]
 [9.99409331e-01]
 [6.35029753e-04]]
Loss: 
3.682182159085657e-07


# 4000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[5.03733933e-04]
 [9.99469439e-01]
 [9.994