## Exercise 1. SOLVIGN A XOR PROBLEM

#### XOR PROBLEM
![XOR](./XOR_problem.jpg)

#### NN example for XOR Problem
![NN_Example](./NN_example.jpg)

In [1]:
import numpy as np

X_train = np.array(([0, 0], [0, 1], [1, 0], [1, 1]), dtype=float)
y_train = np.array(([0], [1], [1], [0]), dtype=float)

X_test = np.array(([0, 0], [0, 1], [1, 0], [1, 1]), dtype=float)
y_test = np.array(([0], [1], [1], [0]), dtype=float)

# scale units
#X_train = X_train / np.amax(X_train, axis=0) # maximum of X array
#X_test = X_test / np.amax(X_test, axis=0) # maximum of X_test (our input data for the prediction)

class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 10

        #weights
        self.w1 = np.random.randn(self.inputSize, self.hiddenSize) # (inputSize x hiddenSize) weight matrix from input to hidden layer
        self.w2 = np.random.randn(self.hiddenSize, self.outputSize) # (hiddenSize x outputSize) weight matrix from hidden to output layer
    
    def forward(self, X):
        #forward propagation through our network
        self.h1_weighted_sum = np.dot(X, self.w1) # dot product of X (input) and first set of (inputSize x hiddenSize) weights
        self.h1_output = self.sigmoid(self.h1_weighted_sum) # activation function
        
        #fill the following (1), (2)
        (1) # dot product of hidden layer (h1_output) and second set of (hiddenSize x outputSize) weights
        (2) # final activation function

        return output

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o, alpha):
        # backward propagate through the network
        self.o_error = (y - o) # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # applying derivative of sigmoid to error

        #fill the following (3), (4), (5), (6)
        (3) # h1 error: how much our hidden layer weights contributed to output error
        (4) # applying derivative of sigmoid to h1_output error
        
        self.w1 += (5) # adjusting first set (input --> hidden) weights
        self.w2 += (6) # adjusting second set (hidden --> output) weights

    def train(self, X, y, alpha):
        o = self.forward(X)
        self.backward(X, y, o, alpha)

    def saveWeights(self):
        np.savetxt("w1.txt", self.w1, fmt="%s")
        np.savetxt("w2.txt", self.w2, fmt="%s")

    def predict(self):
        print("\n\n####################")
        print("Final Results...")
        print("####################\n")
        print("Predicted data based on trained weights: ")
        print("\n<Train data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_train)))
        print("\n<Test data>")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(self.forward(X_test)))

# set a parameter
epoch = int(1e7)
display_step = int(1e6)
alpha = 0.0001        
        
NN = Neural_Network()

for i in range(epoch): # trains the NN 1,000 times
    if i % display_step == 0:
        print("\n# " + str(i) + "\n")
        print("Input: \n" + str(X_train))
        print("Actual Output: \n" + str(y_train))
        print("Predicted Output: \n" + str(NN.forward(X_train)))
        print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
        print()
    NN.train(X_train, y_train, alpha)

print("\n\n####################")
print("Train is Done...")
print("####################\n")

print("\n# " + str(i) + "\n")
print("Input: \n" + str(X_train))
print("Actual Output: \n" + str(y_train))
print("Predicted Output: \n" + str(NN.forward(X_train)))
print("Loss: \n" + str(np.mean(np.square(y_train - NN.forward(X_train)))))# mean sum squared loss
print()

NN.saveWeights()
NN.predict()


# 0

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.07628558]
 [0.08052322]
 [0.38080836]
 [0.37445984]]
Loss: 
0.34371887484394104


# 1000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.25364436]
 [0.6994842 ]
 [0.66202691]
 [0.37520588]]
Loss: 
0.10241261659468442


# 2000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.1467275 ]
 [0.84013452]
 [0.82547575]
 [0.18605464]]
Loss: 
0.028040243250719937


# 3000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.10418785]
 [0.88982014]
 [0.87974432]
 [0.12652805]]
Loss: 
0.013366371124431078


# 4000000

Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.08316579]
 [0.91330042]
 [0.90515657]
 [0.09914835]]
Loss: 
0.0083147594473